### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by eruvanos** [LisaGlaser/send_by_rmapi#1]
HI,
it would be cool to get some hint, how to install this plugin. Never installed a plugin from a repo.

**Comment by LisaGlaser** [comment]
Hi,
Thanks for the question. That's probably a good thing to add to the Readme file.
I used the explanation here to install  https://manual.calibre-ebook.com/creating_plugins.html#the-plugin-api
namel I did 
`calibre-debug -s; calibre-customize -b /path/to/your/plugin/folder; calibre`
Let me know if this works!
Best,
L
